export {
  RAIN_WIND_FACTOR,
  SNOW_WIND_FACTOR,
  CLOUD_WIND_FACTOR,
  MIST_WIND_FACTOR,
  WIND_GUST_VARIANCE,
  RAIN_FALL_SPEED_BASE,
  SNOW_FALL_SPEED_BASE,
  RAIN_FALL_SPEED,
  SNOW_FALL_SPEED,
  THUNDERSTORM_WIND_MULTIPLIER,
  THUNDERSTORM_RAIN_MULTIPLIER,
} from "../../weather-simulation/physics/weatherPhysics";
